watch:
  xdg-open http://localhost:8004
  site watch --port 8004

install:
  cabal install

dev:
  ghcid -Tghcid

commit:
  git add `find _site`
  git commit -m generated
  git add images/* posts/*
  git commit

push:
  git push
